/**
 * ESLint Flat Config (v10+)
 * Eyes of Azrael
 */

module.exports = [
  {
    files: ['js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        HTMLElement: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        AbortController: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        Symbol: 'readonly',
        queueMicrotask: 'readonly',
        structuredClone: 'readonly',
        // Firebase globals
        firebase: 'readonly',
        firebaseConfig: 'readonly',
        // Google Analytics
        gtag: 'readonly',
        dataLayer: 'readonly',
        // Browser globals
        alert: 'readonly',
        confirm: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        XMLHttpRequest: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        Worker: 'readonly',
        Notification: 'readonly',
        indexedDB: 'readonly',
        caches: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        DOMParser: 'readonly',
        // App globals (classes defined by other scripts)
        EyesOfAzrael: 'writable',
        SPANavigation: 'writable',
        RoutePreloader: 'writable',
        ScrollManager: 'writable',
        NavigationMetrics: 'writable',
        RouterAccessibilityManager: 'writable',
        AccessibilityManager: 'writable',
        AuthManager: 'writable',
        FirebaseCRUDManager: 'writable',
        UniversalDisplayRenderer: 'writable',
        EnhancedCorpusSearch: 'writable',
        CorpusSearch: 'writable',
        ShaderThemeManager: 'writable',
        EditEntityModal: 'writable',
        LandingPageView: 'writable',
        HomeView: 'writable',
        BrowseCategoryView: 'writable',
        MythologiesView: 'writable',
        PageAssetRenderer: 'writable',
        FirebaseCacheManager: 'writable',
        ToastNotification: 'writable',
        AssetService: 'writable',
        UserPreferencesService: 'writable',
        ContentFilter: 'writable',
        CompareView: 'writable',
        ContributeMenu: 'writable',
        // Init-time functions (defined by error-monitoring.js, etc.)
        initErrorMonitoring: 'readonly',
        initPerformanceMonitoring: 'readonly',
        StartupChecklist: 'readonly',
        // Module exports
        module: 'readonly',
        exports: 'readonly',
        require: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
      }
    },
    rules: {
      'no-debugger': 'error',
      'no-console': 'off',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'eqeqeq': ['warn', 'smart'],
      'no-eval': 'error',
      'no-implied-eval': 'error',
    }
  },
  {
    // Ignore patterns
    ignores: [
      'node_modules/**',
      'coverage/**',
      'dist/**',
      'js/**/*.min.js',
      'firebase-assets-*/**',
      'scripts/**',
      '__tests__/**',
      'e2e/**',
      '*.config.js',
    ]
  }
];
